### PR TITLE
Update the extension to modern API.

### PR DESCRIPTION
**Pull request by akabaev**
This set of changes updates the extension to work without deprecations
warnings with inkscape 1.0.

This is mostly mechanical. I do not have TimSav yet to verify the output for correct information and proper scaling.

### CODE REVIEW

**Comment by UncoolAsianDad** [comment]
nice. thanks for the updates. I am going to create a pre1.0 branch and then make post 1.0 the main branch.

**Comment by KawateiHikaru** [comment]
nice. thanks for the updates. I am going to create a pre1.0 branch and then make post 1.0 the main branch.

**Comment by KawateiHikaru** [comment]
nice. thanks for the updates. I am going to create a pre1.0 branch and then make post 1.0 the main branch.

**Comment by UncoolAsianDad** [comment]
I did some quick test and got some error.
`C:\Users\Hikaru\AppData\Roaming\inkscape\extensions\unicorn\svg_parser.py:109: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"
  newpath = inkex.etree.Element(inkex.addNS('path','svg'))
Traceback (most recent call last):
  File "unicorn.py", line 114, in <module>
    e.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 123, in run
    self.save_raw(self.effect())
  File "unicorn.py", line 108, in effect
    parser.parse()
  File "C:\Users\Hikaru\AppData\Roaming\inkscape\extensions\unicorn\svg_parser.py", line 254, in parse
    self.recursivelyTraverseSvg(self.svg, Transform([[1.0, 0.0, 0], [0.0, -1.0, self.svgHeight]]))
  File "C:\Users\Hikaru\AppData\Roaming\inkscape\extensions\unicorn\svg_parser.py", line 291, in recursivelyTraverseSvg
    self.recursivelyTraverseSvg(node, transNew, parent_visibility = v)
  File "C:\Users\Hikaru\AppData\Roaming\inkscape\extensions\unicorn\svg_parser.py", line 315, in recursivelyTraverseSvg
    entity = self.make_entity(node, transNew)
  File "C:\Users\Hikaru\AppData\Roaming\inkscape\extensions\unicorn\svg_parser.py", line 329, in make_entity
    entity.load(node,trans)
  File "C:\Users\Hikaru\AppData\Roaming\inkscape\extensions\unicorn\svg_parser.py", line 131, in load
    newpath.set('d', str(paths.Path(a)))
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\paths.py", line 1034, in __init__
    self.append(PathCommand.letter_to_class(item[0])(*item[1]))
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\paths.py", line 109, in letter_to_class
    return PathCommand._letter_to_class[letter]
KeyError: 'M '
`

I won't be able to look into it until much later, or if you can fix it. that would be great. I am on Windows 10.

**Review by UncoolAsianDad — COMMENTED** [review]
another quick question, do you know of any good way to have unit tests running against the extension? I can't seem to figure out how to mock/inject the core Inkscape modules.

**Comment by akabaev** [comment]
Not really, but there are handful of shapes we need to cover to test the whole extension really. If you get deprecation warning, it means I missed some. Can I have the test STL file that triggers the issue?

**Comment by akabaev** [comment]
Never mind, I see the problem. Please find quick fix for deprecated use for inkex.etree meanwhile. I'll fix trivial figures when I have the chance, probably later today.

**Comment by akabaev** [comment]
OK, SVG rectangles and lines will now be parsed correctly.

**Comment by UncoolAsianDad** [comment]
used the new commit on Inkscape 1.0rc1, worked, thanks for the PR!

**Pull request merged**
